apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths" : {
        "cp.icr.io" : {
          "auth" : "cp",
          "identitytoken" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE3MDUwMDE4MjksImp0aSI6ImMzODRmZTM5MDFjNzRhOTlhMTExZTdmNzQwNGVhOTE5In0.Zfwpv7ZSpsmGJESIPYtzVmGwjmDVpRgtPGqSHYE7RDY"
        }
      }
    }
